#!/usr/bin/env bash
# bootstrap.sh — Prima Terminal Concept Bootstrap
# Idempotent: safe to run more than once.

set -euo pipefail

PRIMA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DOTFILES_DIR="$PRIMA_DIR/seeds/dotfiles"
PACKAGES_FILE="$PRIMA_DIR/seeds/packages.yaml"

echo "==> Prima Terminal: bootstrapping..."

# ---------------------------------------------------------------------------
# 1. Package installation
# ---------------------------------------------------------------------------
# Reads seeds/packages.yaml for manager + required packages.
PREFERRED_MANAGER=""
if [ -f "$PACKAGES_FILE" ]; then
    PREFERRED_MANAGER="$(awk '
        /^manager:/ {
            value=$0
            sub(/^manager:[[:space:]]*/, "", value)
            sub(/[[:space:]]+#.*$/, "", value)
            gsub(/[[:space:]]+$/, "", value)
            gsub(/["\047]/, "", value)
            print value
            exit
        }
    ' "$PACKAGES_FILE")"
fi

if [ -n "$PREFERRED_MANAGER" ] && [ "$PREFERRED_MANAGER" != "auto" ]; then
    if command -v "$PREFERRED_MANAGER" &>/dev/null; then
        MANAGER="$PREFERRED_MANAGER"
    else
        echo "WARN: Preferred manager '$PREFERRED_MANAGER' not found; auto-detecting."
        MANAGER=""
    fi
else
    MANAGER=""
fi

if [ -z "$MANAGER" ]; then
    if command -v pkg &>/dev/null; then
        MANAGER="pkg"
    elif command -v apt-get &>/dev/null; then
        MANAGER="apt-get"
    else
        echo "WARN: No supported package manager found. Install packages manually."
        MANAGER="none"
    fi
fi

REQUIRED_PACKAGES=()
if [ -f "$PACKAGES_FILE" ]; then
    while IFS= read -r package; do
        REQUIRED_PACKAGES+=("$package")
    done < <(awk '
        /^required:[[:space:]]*$/ { in_required=1; next }
        in_required && /^[[:space:]]*-[[:space:]]*/ {
            sub(/^[[:space:]]*-[[:space:]]*/, "", $0)
            sub(/[[:space:]]+#.*$/, "", $0)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
            if ($0 == "") next
            gsub(/["\047]/, "", $0)
            print $0
            next
        }
        in_required && /^[^[:space:]]/ { in_required=0 }
    ' "$PACKAGES_FILE")
fi

if [ ${#REQUIRED_PACKAGES[@]} -eq 0 ]; then
    REQUIRED_PACKAGES=(git curl)
fi

if [ "$MANAGER" != "none" ]; then
    echo "==> Installing required packages via $MANAGER..."
    "$MANAGER" install -y "${REQUIRED_PACKAGES[@]}"
fi

# ---------------------------------------------------------------------------
# 2. Dotfile deployment
# ---------------------------------------------------------------------------
if [ -d "$DOTFILES_DIR" ]; then
    echo "==> Deploying dotfiles from $DOTFILES_DIR..."
    shopt -s nullglob
    dotfile_sources=("$DOTFILES_DIR"/.*)
    shopt -u nullglob
    for src in "${dotfile_sources[@]}"; do
        fname="$(basename "$src")"
        # Skip . and ..
        [ "$fname" = "." ] || [ "$fname" = ".." ] && continue
        dest="$HOME/$fname"
        if [ -e "$dest" ]; then
            echo "  SKIP $fname (already exists at $dest)"
        else
            cp -R "$src" "$dest"
            echo "  OK   $fname → $dest"
        fi
    done
else
    echo "  (no dotfiles directory found — skipping)"
fi

# ---------------------------------------------------------------------------
# 3. Concept environment marker
# ---------------------------------------------------------------------------
PRIMA_ENV="$HOME/.prima-env"
if [ ! -f "$PRIMA_ENV" ]; then
    PRIMA_CONCEPT_VALUE="$(grep '^  name:' "$PRIMA_DIR/prima.yaml" 2>/dev/null | head -1 | sed 's/^  name: *//' | tr -d '"' | tr -d "'")"
    PRIMA_VERSION_VALUE="$(grep '^  version:' "$PRIMA_DIR/prima.yaml" 2>/dev/null | head -1 | sed 's/^  version: *//' | tr -d '"' | tr -d "'")"
    {
        echo "# Prima Terminal Environment"
        echo "# Auto-generated by bootstrap.sh — edit freely."
        printf 'PRIMA_CONCEPT=%q\n' "$PRIMA_CONCEPT_VALUE"
        printf 'PRIMA_VERSION=%q\n' "$PRIMA_VERSION_VALUE"
        printf 'PRIMA_ROOT=%q\n' "$PRIMA_DIR"
    } > "$PRIMA_ENV"
    echo "==> Created $PRIMA_ENV"
fi

echo "==> Bootstrap complete. Open a new shell or run: source ~/.prima-env"
